services:
  deceased-craft-server:
    container_name: deceased-craft-server
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "20432:25565" # Main server port
      - "20433:20433/udp" # Voice chat port
    restart: unless-stopped
    environment:
      # General
      UID: 1001
      GID: 1001
      MEMORY: "12G"
      USE_AIKAR_FLAGS: "true"
      TZ: "CST"

      # Server
      SERVER_NAME: "DeceasedCraft"
      TYPE: AUTO_CURSEFORGE
      EULA: TRUE
      DIFFICULTY: normal
      ICON: "./CursedVillager.png"
      SPAWN_PROTECTION: 0
      VIEW_DISTANCE: 12
      LEVEL: world
      SEED: "8039373677206551754"
      ONLINE_MODE: true
      STOP_SERVER_ANNOUNCE_DELAY: 5
      ENFORCE_SECURE_PROFILE: false
      EXEC_DIRECTLY: true
      MOTD: "§2-=§c§l DeceasedCraft§2 =-§r

        \    ᓚᘏᗢ    ಠ_ಠ"

      # RCON
      ENABLE_RCON: true
      RCON_PASSWORD: "password"

      # CurseForge
      CF_API_KEY: ${CF_API_KEY}
      CF_SLUG: deceasedcraft
      CF_FILENAME_MATCHER: 5.5.5
      CF_EXCLUDE_MODS: true-darkness

    volumes:
      # attach the relative directory 'data' to the container's /data path
      - ./data:/data
      # Downloads used for manual mod downloads
      - ./downloads:/downloads
